/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as MediaUploadTokenRouteImport } from './routes/media-upload.$token'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaUploadTokenRoute = MediaUploadTokenRouteImport.update({
  id: '/media-upload/$token',
  path: '/media-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/database': typeof DatabaseRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/voice': typeof VoiceRoute
  '/media-upload/$token': typeof MediaUploadTokenRoute
  '/review/$token': typeof ReviewTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/database': typeof DatabaseRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/voice': typeof VoiceRoute
  '/media-upload/$token': typeof MediaUploadTokenRoute
  '/review/$token': typeof ReviewTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/database': typeof DatabaseRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/voice': typeof VoiceRoute
  '/media-upload/$token': typeof MediaUploadTokenRoute
  '/review/$token': typeof ReviewTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/database'
    | '/login'
    | '/marketing'
    | '/reset-password'
    | '/voice'
    | '/media-upload/$token'
    | '/review/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/database'
    | '/login'
    | '/marketing'
    | '/reset-password'
    | '/voice'
    | '/media-upload/$token'
    | '/review/$token'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/database'
    | '/login'
    | '/marketing'
    | '/reset-password'
    | '/voice'
    | '/media-upload/$token'
    | '/review/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DatabaseRoute: typeof DatabaseRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VoiceRoute: typeof VoiceRoute
  MediaUploadTokenRoute: typeof MediaUploadTokenRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-upload/$token': {
      id: '/media-upload/$token'
      path: '/media-upload/$token'
      fullPath: '/media-upload/$token'
      preLoaderRoute: typeof MediaUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DatabaseRoute: DatabaseRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VoiceRoute: VoiceRoute,
  MediaUploadTokenRoute: MediaUploadTokenRoute,
  ReviewTokenRoute: ReviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
